name: "Clean permissions"
description: "Sets all permissions in github work dir to current user"
  
runs:
  using: "composite"
  steps:  
      - name: Fix permissions from prev jobs (docker creates files as root)
        shell: bash
        run: |
          echo TODO this is not a long term solution as each job in each workflow file needs to execute this
          sudo chown -R $USER:$USER $GITHUB_WORKSPACE